version: "3.8"

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lengotengo
    ports:
      - "5433:5432"
    volumes:
      - ./pg-volume:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
